-- Insert books (skip if already exist)
INSERT INTO books (title, author, summary, publication_date, total_quantity, available_quantity, cover_image)
VALUES
  ('To Kill a Mockingbird', 'Harper Lee', 'A novel about racial injustice in the Deep South, seen through the eyes of young Scout Finch.', '1960-07-11', 3, 3, 'to-kill-a-mockingbird.jpg'),
  ('1984', 'George Orwell', 'A dystopian novel set in a totalitarian society ruled by Big Brother.', '1949-06-08', 5, 5, '1984.jpg'),
  ('The Great Gatsby', 'F. Scott Fitzgerald', 'A story of the Jazz Age, wealth, and the American Dream.', '1925-04-10', 3, 3, 'the-great-gatsby.jpg'),
  ('Pride and Prejudice', 'Jane Austen', 'A romantic novel following Elizabeth Bennet as she navigates issues of manners, morality, and marriage.', '1813-01-28', 4, 4, 'pride-and-prejudice.jpg'),
  ('The Catcher in the Rye', 'J.D. Salinger', 'A story about teenage angst and alienation, told by Holden Caulfield.', '1951-07-16', 2, 2, 'the-catcher-in-the-rye.jpg'),
  ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 'The multi-generational story of the Buendia family in the fictional town of Macondo.', '1967-05-30', 3, 3, 'one-hundred-years-of-solitude.jpg'),
  ('Brave New World', 'Aldous Huxley', 'A futuristic society where humans are genetically modified and socially conditioned.', '1932-01-01', 4, 4, 'brave-new-world.jpg'),
  ('The Lord of the Rings', 'J.R.R. Tolkien', 'An epic fantasy quest to destroy the One Ring and defeat the Dark Lord Sauron.', '1954-07-29', 5, 5, 'the-lord-of-the-rings.jpg'),
  ('Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 'A young boy discovers he is a wizard and attends Hogwarts School of Witchcraft and Wizardry.', '1997-06-26', 6, 6, 'harry-potter-and-the-philosopher-s-stone.jpg'),
  ('The Hobbit', 'J.R.R. Tolkien', 'Bilbo Baggins embarks on an unexpected journey with a group of dwarves to reclaim their homeland.', '1937-09-21', 4, 4, 'the-hobbit.jpg'),
  ('Fahrenheit 451', 'Ray Bradbury', 'A fireman tasked with burning books begins to question his role in a censorship-obsessed society.', '1953-10-19', 3, 3, 'fahrenheit-451.jpg'),
  ('Jane Eyre', 'Charlotte Bronte', 'An orphaned governess falls in love with her brooding employer, only to discover his dark secret.', '1847-10-16', 3, 3, 'jane-eyre.jpg'),
  ('Animal Farm', 'George Orwell', 'A satirical allegory of Stalinism, told through farm animals who overthrow their human farmer.', '1945-08-17', 4, 4, 'animal-farm.jpg'),
  ('The Alchemist', 'Paulo Coelho', 'A shepherd boy travels from Spain to Egypt in search of treasure, learning life lessons along the way.', '1988-01-01', 5, 5, 'the-alchemist.jpg'),
  ('Crime and Punishment', 'Fyodor Dostoevsky', 'A young intellectual commits murder and struggles with guilt and moral dilemmas.', '1866-01-01', 3, 3, 'crime-and-punishment.jpg'),
  ('The Adventures of Huckleberry Finn', 'Mark Twain', 'A boy and an escaped slave travel down the Mississippi River on a raft.', '1884-12-10', 3, 3, 'the-adventures-of-huckleberry-finn.jpg'),
  ('Wuthering Heights', 'Emily Bronte', 'A tale of intense passion and revenge set on the Yorkshire moors.', '1847-12-01', 3, 3, 'wuthering-heights.jpg'),
  ('The Picture of Dorian Gray', 'Oscar Wilde', 'A man remains youthful while his portrait ages, reflecting his moral decay.', '1890-06-20', 3, 3, 'the-picture-of-dorian-gray.jpg'),
  ('Moby-Dick', 'Herman Melville', 'Captain Ahab obsessively hunts a giant white whale aboard the Pequod.', '1851-10-18', 2, 2, 'moby-dick.jpg'),
  ('Don Quixote', 'Miguel de Cervantes', 'An aging gentleman becomes convinced he is a knight and sets out on absurd adventures.', '1605-01-16', 3, 3, 'don-quixote.jpg'),
  ('The Brothers Karamazov', 'Fyodor Dostoevsky', 'Three brothers grapple with faith, free will, and morality after their father is murdered.', '1880-11-01', 2, 2, 'the-brothers-karamazov.jpg'),
  ('Les Miserables', 'Victor Hugo', 'Ex-convict Jean Valjean seeks redemption amid the backdrop of revolutionary France.', '1862-01-01', 4, 4, 'les-miserables.jpg'),
  ('The Count of Monte Cristo', 'Alexandre Dumas', 'Edmond Dantes escapes prison and seeks vengeance against those who wronged him.', '1844-01-01', 4, 4, 'the-count-of-monte-cristo.jpg'),
  ('Anna Karenina', 'Leo Tolstoy', 'A married aristocrat falls into a tragic love affair that leads to her downfall.', '1878-01-01', 3, 3, 'anna-karenina.jpg'),
  ('War and Peace', 'Leo Tolstoy', 'An epic novel intertwining the lives of aristocratic families during the Napoleonic Wars.', '1869-01-01', 2, 2, 'war-and-peace.jpg'),
  ('The Odyssey', 'Homer', 'Odysseus journeys home after the Trojan War, facing mythical creatures and divine challenges.', '1726-04-01', 3, 3, 'the-odyssey.jpg'),
  ('Dracula', 'Bram Stoker', 'Count Dracula travels from Transylvania to England to spread the undead curse.', '1897-05-26', 4, 4, 'dracula.jpg'),
  ('Frankenstein', 'Mary Shelley', 'Victor Frankenstein creates a sentient creature in a scientific experiment gone awry.', '1818-01-01', 4, 4, 'frankenstein.jpg'),
  ('The Divine Comedy', 'Dante Alighieri', 'Dante journeys through Hell, Purgatory, and Paradise guided by Virgil and Beatrice.', '1320-01-01', 2, 2, 'the-divine-comedy.jpg'),
  ('Alice''s Adventures in Wonderland', 'Lewis Carroll', 'A girl falls down a rabbit hole into a fantasy world of peculiar creatures.', '1865-11-26', 3, 3, 'alice-s-adventures-in-wonderland.jpg'),
  ('The Little Prince', 'Antoine de Saint-Exupery', 'A young prince from a distant asteroid shares lessons about love, loss, and human nature.', '1943-04-06', 5, 5, 'the-little-prince.jpg'),
  ('Gone with the Wind', 'Margaret Mitchell', 'Scarlett O''Hara struggles to survive and rebuild her life during the American Civil War.', '1936-06-30', 3, 3, 'gone-with-the-wind.jpg'),
  ('Slaughterhouse-Five', 'Kurt Vonnegut', 'Billy Pilgrim becomes unstuck in time, experiencing World War II and alien abduction.', '1969-03-31', 3, 3, 'slaughterhouse-five.jpg'),
  ('The Grapes of Wrath', 'John Steinbeck', 'A family of displaced sharecroppers journeys from Oklahoma to California during the Dust Bowl.', '1939-04-14', 3, 3, 'the-grapes-of-wrath.jpg'),
  ('Of Mice and Men', 'John Steinbeck', 'Two migrant ranch workers dream of owning land during the Great Depression.', '1937-02-25', 3, 3, 'of-mice-and-men.jpg'),
  ('Lolita', 'Vladimir Nabokov', 'A middle-aged literature professor becomes obsessed with a twelve-year-old girl.', '1955-01-01', 2, 2, 'lolita.jpg'),
  ('Catch-22', 'Joseph Heller', 'A bomber pilot tries to avoid combat missions in World War II under a paradoxical rule.', '1961-10-10', 3, 3, 'catch-22.jpg'),
  ('The Sun Also Rises', 'Ernest Hemingway', 'A group of expatriates travels from Paris to Spain after World War I.', '1926-10-22', 3, 3, 'the-sun-also-rises.jpg'),
  ('A Farewell to Arms', 'Ernest Hemingway', 'An American ambulance driver falls in love with a British nurse during World War I.', '1929-09-27', 3, 3, 'a-farewell-to-arms.jpg'),
  ('The Old Man and the Sea', 'Ernest Hemingway', 'An aging fisherman battles a giant marlin in the Gulf Stream.', '1952-09-01', 3, 3, 'the-old-man-and-the-sea.jpg'),
  ('Beloved', 'Toni Morrison', 'A former slave is haunted by the ghost of her baby daughter after escaping slavery.', '1987-09-02', 2, 2, 'beloved.jpg'),
  ('The Handmaid''s Tale', 'Margaret Atwood', 'A woman forced into sexual servitude in a totalitarian theocracy seeks to survive and escape.', '1985-08-01', 4, 4, 'the-handmaid-s-tale.jpg'),
  ('The Road', 'Cormac McCarthy', 'A father and son journey through a post-apocalyptic America, struggling to survive.', '2006-09-26', 3, 3, 'the-road.jpg'),
  ('No Country for Old Men', 'Cormac McCarthy', 'A hunter stumbles upon a drug deal gone wrong and a psychopathic killer pursues him.', '2005-07-19', 3, 3, 'no-country-for-old-men.jpg'),
  ('The Name of the Rose', 'Umberto Eco', 'A medieval Franciscan friar investigates a series of mysterious deaths in a secluded abbey.', '1980-01-01', 3, 3, 'the-name-of-the-rose.jpg'),
  ('The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 'Arthur Dent is whisked off Earth moments before its destruction for an interstellar hitchhiking adventure.', '1979-10-12', 4, 4, 'the-hitchhiker-s-guide-to-the-galaxy.jpg'),
  ('Dune', 'Frank Herbert', 'On the desert planet Arrakis, a young nobleman leads a rebellion to control the spice melange.', '1965-08-01', 5, 5, 'dune.jpg'),
  ('Neuromancer', 'William Gibson', 'A washed-up computer hacker is hired for one last job in a cyberpunk future.', '1984-07-01', 3, 3, 'neuromancer.jpg'),
  ('The Shining', 'Stephen King', 'A family becomes caretakers of an isolated hotel where supernatural forces drive the father to madness.', '1977-01-28', 3, 3, 'the-shining.jpg'),
  ('It', 'Stephen King', 'Seven childhood friends must confront a shape-shifting evil entity that awakens every 27 years.', '1986-09-15', 3, 3, 'it.jpg'),
  ('The Da Vinci Code', 'Dan Brown', 'A symbologist uncovers a religious mystery hidden in Leonardo da Vinci''s works.', '2003-03-18', 5, 5, 'the-da-vinci-code.jpg'),
  ('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'A journalist and a hacker investigate a decades-old disappearance of a wealthy heiress.', '2005-08-01', 4, 4, 'the-girl-with-the-dragon-tattoo.jpg'),
  ('Life of Pi', 'Yann Martel', 'A teenage boy survives a shipwreck and shares a lifeboat with a Bengal tiger.', '2001-09-11', 3, 3, 'life-of-pi.jpg'),
  ('The Kite Runner', 'Khaled Hosseini', 'A young boy from Kabul witnesses a traumatic event that haunts him into adulthood.', '2003-05-29', 4, 4, 'the-kite-runner.jpg'),
  ('Memoirs of a Geisha', 'Arthur Golden', 'A young girl is sold into the geisha district of Kyoto and rises to become a celebrated geisha.', '1997-09-01', 3, 3, 'memoirs-of-a-geisha.jpg')
ON CONFLICT (title, author) DO NOTHING;
